--select * from customer

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue_by_gender
from customer
group by gender;




--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);



-- Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased, 
avg(review_rating) as avg_rating
from customer
group by item_purchased
order by avg_rating desc;




--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type,
avg(purchase_amount) as avg_revenue_by_shipping 
from customer
where shipping_type in ('Express','Standard')
group by shipping_type;




--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status, 
round(avg(purchase_amount),2) as avg_spend,  
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_spend desc;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select * from customer

select top 5 item_purchased, 
round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(item_purchased), 2) as pct
from customer
group by item_purchased
order by pct desc



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cte_customer_segment as
(
select customer_id, previous_purchases,
case when previous_purchases < 10 then 'New'
when previous_purchases >=10 and previous_purchases <= 25 then 'Returning'
when previous_purchases > 25 then 'Loyal'
end customer_segment
from customer
)
select customer_segment, count(customer_id) as customer_count
from cte_customer_segment
group by customer_segment;



--Q8. What are the top 3 most purchased products within each category? 
with cte_rank as
(
select item_purchased, category, 
count(item_purchased) as item_count,
row_number() over (partition by category order by count(item_purchased) desc) as rk
from customer
group by item_purchased, category
)

select item_purchased, category, rk from cte_rank
where rk <= 3;






--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select  subscription_status, count(customer_id)
from customer
where previous_purchases > 5
group by subscription_status;



--Q10. What is the revenue contribution of each age group? 

select age_group, sum(purchase_amount) as revenue_by_age_group
from customer
group by age_group;